<?php

declare(strict_types=1);

/**
 * Mobaro Installer
 * ---------------
 * Fresh-install wizard for marketplace delivery.
 * Writes .env from the form, verifies the DB connection, imports the
 * schema (+ optional demo seed) and creates the first admin account.
 *
 * After a successful install this file MUST be deleted.
 * Access: https://your-domain.com/install.php
 */

error_reporting(E_ALL);
ini_set('display_errors', '1');

$baseDir = __DIR__;
$envPath = $baseDir . '/.env';
$lockPath = $baseDir . '/install.lock';

$alreadyInstalled = false;
if (is_file($envPath)) {
    $envContent = (string) file_get_contents($envPath);
    $alreadyInstalled = str_contains($envContent, 'DB_NAME=') && preg_match('/^DB_NAME=.+/m', $envContent) === 1;
}

$steps = ['info', 'form', 'done'];
$step = $_GET['step'] ?? 'form';
if ($alreadyInstalled && ($step === 'form' || $step === 'info')) {
    $step = 'done';
}
if (!in_array($step, $steps, true)) {
    $step = 'form';
}

$error = '';
$db = null;

function normalizePhone(string $phone): string
{
    $phone = trim($phone);
    $phone = preg_replace('/[^\d+]/', '', $phone);
    if (str_starts_with($phone, '+98')) {
        $phone = '0' . substr($phone, 3);
    } elseif (str_starts_with($phone, '98')) {
        $phone = '0' . substr($phone, 2);
    }
    return $phone;
}

function writeEnvFile(string $path, array $values): bool
{
    $content = "# Auto-generated by install.php — edit safely after install\n"
        . "APP_NAME=" . ($values['app_name'] ?? 'موبارو') . "\n"
        . "APP_URL=" . rtrim((string) ($values['app_url'] ?? ''), '/') . "\n"
        . "APP_ENV=production\n"
        . "APP_DEBUG=false\n\n"
        . "DB_HOST=" . ($values['db_host'] ?? 'localhost') . "\n"
        . "DB_NAME=" . ($values['db_name'] ?? '') . "\n"
        . "DB_USER=" . ($values['db_user'] ?? '') . "\n"
        . "DB_PASS=" . ($values['db_pass'] ?? '') . "\n"
        . "DB_CHARSET=" . ($values['db_charset'] ?? 'utf8mb4') . "\n\n"
        . "CACHE_PREFIX=mobaro\n"
        . "CACHE_DIR=\n"
        . "CACHE_TTL_DEFAULT=3600\n"
        . "CACHE_TTL_PAGE=600\n"
        . "CACHE_TTL_ADMIN=300\n\n"
        . "ZARINPAL_MERCHANT_ID=\n"
        . "ZARINPAL_SANDBOX=true\n\n"
        . "GOOGLE_CLIENT_ID=\n"
        . "GOOGLE_CLIENT_SECRET=\n"
        . "GOOGLE_REDIRECT_URI=" . rtrim((string) ($values['app_url'] ?? ''), '/') . "/auth/google/callback\n\n"
        . "# SMS (sms.ir)\n"
        . "SMS_ENABLED=false\n"
        . "SMS_API_KEY=\n"
        . "SMS_TEMPLATE_ID=\n"
        . "SMS_LINE_NUMBER=\n"
        . "SMS_OTP_TTL=180\n"
        . "SMS_OTP_LENGTH=5\n\n"
        . "# TinyMCE\n"
        . "TINYMCE_API_KEY=no-api-key\n";

    return file_put_contents($path, $content, LOCK_EX) !== false;
}

function execSqlFile(PDO $pdo, string $file): array
{
    $messages = [];
    $sql = file_get_contents($file);
    if ($sql === false) {
        return ['[خطا] فایل ' . basename($file) . ' پیدا نشد.'];
    }

    // Strip full-line comments first so a statement chunk never begins with them.
    $lines = array_filter(
        explode("\n", $sql),
        fn(string $l): bool => !str_starts_with(ltrim($l), '--') && !str_starts_with(ltrim($l), '/*')
    );
    $sql = implode("\n", $lines);

    $statements = array_filter(
        array_map('trim', explode(';', $sql)),
        fn(string $s): bool => $s !== ''
            && !str_starts_with($s, '--') && !str_starts_with($s, '/*')
            && !str_starts_with($s, 'CREATE DATABASE') && !str_starts_with($s, 'USE ')
            && !str_starts_with($s, 'DELIMITER')
    );

    foreach ($statements as $stmt) {
        $pdo->exec($stmt);
    }
    $messages[] = '[OK] ' . basename($file) . ' اجرا شد (' . count($statements) . ' دستور).';
    return $messages;
}

if (($_SERVER['REQUEST_METHOD'] ?? 'GET') === 'POST' && $step === 'form') {
    if ($alreadyInstalled) {
        $step = 'done';
    } else {
        $dbHost = trim((string) ($_POST['db_host'] ?? ''));
        $dbName = trim((string) ($_POST['db_name'] ?? ''));
        $dbUser = trim((string) ($_POST['db_user'] ?? ''));
        $dbPass = (string) ($_POST['db_pass'] ?? '');
        $dbCharset = trim((string) ($_POST['db_charset'] ?? 'utf8mb4'));
        $appName = trim((string) ($_POST['app_name'] ?? ''));
        $appUrl = trim((string) ($_POST['app_url'] ?? ''));
        $phone = normalizePhone((string) ($_POST['phone'] ?? ''));
        $password = (string) ($_POST['password'] ?? '');
        $password2 = (string) ($_POST['password2'] ?? '');
        $withSeed = isset($_POST['with_seed']);
        $createDb = isset($_POST['create_db']);

        if ($dbHost === '' || $dbName === '' || $dbUser === '') {
            $error = 'مشخصات دیتابیس (host، name و user) اجباری است.';
        } elseif ($appName === '' || $appUrl === '') {
            $error = 'نام سایت و آدرس دامنه اجباری است.';
        } elseif ($phone === '' || !preg_match('/^09\d{9}$/', $phone)) {
            $error = 'شماره موبایل معتبر نیست (مثال: ۰۹۱۲۳۴۵۶۷۸۹).';
        } elseif (strlen($password) < 6) {
            $error = 'رمز عبور باید حداقل ۶ کاراکتر باشد.';
        } elseif ($password !== $password2) {
            $error = 'رمز عبور و تکرار آن یکسان نیستند.';
        } else {
            try {
                $dsn = "mysql:host={$dbHost};charset={$dbCharset}";
                $db = new PDO($dsn, $dbUser, $dbPass, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                ]);

                if ($createDb) {
                    $db->exec(
                        "CREATE DATABASE IF NOT EXISTS `" . str_replace('`', '', $dbName)
                        . "` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci"
                    );
                }

                $db->exec("USE `" . str_replace('`', '', $dbName) . "`");

                if (!is_writable($baseDir)) {
                    throw new RuntimeException('پوشه اصلی قابل نوشتن نیست (برای ساخت .env).');
                }

                $messages = execSqlFile($db, $baseDir . '/database/schema.sql');

                $hashed = password_hash($password, PASSWORD_BCRYPT);
                $stmt = $db->prepare(
                    "INSERT INTO users (name, family, phone, password, role, is_active)
                     VALUES ('مدیر', 'سیستم', ?, ?, 'admin', 1)
                     ON DUPLICATE KEY UPDATE password = VALUES(password)"
                );
                $stmt->execute([$phone, $hashed]);
                $messages[] = '[OK] حساب مدیر ساخته شد.';

                if ($withSeed) {
                    $seedMessages = execSqlFile($db, $baseDir . '/database/seed.sql');
                    $messages = array_merge($messages, $seedMessages);
                    $db->exec("DELETE FROM users WHERE role = 'admin' AND phone <> " . $db->quote($phone));
                }

                writeEnvFile($envPath, [
                    'app_name' => $appName,
                    'app_url' => $appUrl,
                    'db_host' => $dbHost,
                    'db_name' => $dbName,
                    'db_user' => $dbUser,
                    'db_pass' => $dbPass,
                    'db_charset' => $dbCharset,
                ]);

                @file_put_contents($lockPath, date('c'), LOCK_EX);

                $step = 'done';
                $_SESSION = [];
            } catch (PDOException $e) {
                $error = 'خطای دیتابیس: ' . htmlspecialchars($e->getMessage());
            } catch (Throwable $e) {
                $error = 'خطا: ' . htmlspecialchars($e->getMessage());
            }
        }
    }
}
?>
<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>نصب موبارو</title>
<style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', Tahoma, sans-serif; background: linear-gradient(135deg, #fdf2f8 0%, #fce7f3 100%); min-height: 100vh; display: flex; align-items: center; justify-content: center; padding: 24px; }
    .card { background: #fff; border-radius: 20px; padding: 36px; max-width: 560px; width: 100%; box-shadow: 0 8px 40px rgba(225,29,72,0.10); }
    h1 { color: #e11d48; font-size: 1.5rem; text-align: center; margin-bottom: 6px; }
    .subtitle { color: #71717a; font-size: .875rem; text-align: center; margin-bottom: 24px; }
    .error { background: #fef2f2; color: #dc2626; padding: 12px 14px; border-radius: 10px; margin-bottom: 16px; font-size: .875rem; text-align: center; }
    .success { background: #f0fdf4; color: #166534; padding: 16px; border-radius: 12px; font-size: .95rem; line-height: 1.9; }
    .success strong { display: block; font-size: 1.1rem; margin-bottom: 8px; color: #15803d; }
    .log { background: #fafafa; border: 1px solid #f1f1f1; border-radius: 10px; padding: 12px; margin: 12px 0; font-size: .8rem; color: #3f3f46; line-height: 1.8; }
    label { display: block; font-size: .85rem; font-weight: 600; margin: 14px 0 6px; color: #3f3f46; }
    input { width: 100%; padding: 11px 14px; border: 2px solid #fce7f3; border-radius: 12px; font-size: .95rem; outline: none; transition: border-color .2s; }
    input:focus { border-color: #e11d48; }
    .section { background: #fff7fa; border-radius: 12px; padding: 2px 16px 14px; margin-top: 18px; }
    .section h2 { font-size: .9rem; color: #be185d; margin-top: 14px; }
    .row { display: grid; grid-template-columns: 1fr 1fr; gap: 0 12px; }
    .check { display: flex; align-items: center; gap: 8px; margin-top: 14px; font-size: .85rem; color: #52525b; }
    .check input { width: auto; }
    button { width: 100%; padding: 14px; background: #e11d48; color: #fff; border: none; border-radius: 12px; font-size: 1rem; font-weight: 700; cursor: pointer; margin-top: 22px; transition: background .2s; }
    button:hover { background: #be185d; }
    .warn { background: #fffbeb; color: #b45309; padding: 12px; border-radius: 10px; margin-top: 14px; font-size: .8rem; text-align: center; }
</style>
</head>
<body>
<div class="card">
    <h1>mobaro</h1>
    <p class="subtitle">دستیار نصب</p>

    <?php if ($step === 'info'): ?>
        <p style="font-size:.9rem;color:#3f3f46;line-height:1.9;">
            این دستیار فایل <code>.env</code> را می‌سازد، اتصال دیتابیس را بررسی می‌کند،
            جدول‌های مورد نیاز را می‌سازد و اولین حساب مدیر را ثبت می‌کند.
        </p>
        <form method="get" style="margin-top:20px;">
            <input type="hidden" name="step" value="form">
            <button type="submit">شروع نصب</button>
        </form>
    <?php elseif ($step === 'form'): ?>

        <?php if ($error !== ''): ?>
            <div class="error"><?= $error ?></div>
        <?php endif; ?>

        <form method="POST">
            <div class="section">
                <h2>دیتابیس</h2>
                <div class="row">
                    <div>
                        <label>Host</label>
                        <input type="text" name="db_host" value="localhost" required dir="ltr">
                    </div>
                    <div>
                        <label>نام دیتابیس</label>
                        <input type="text" name="db_name" required dir="ltr" placeholder="mobaro">
                    </div>
                </div>
                <div class="row">
                    <div>
                        <label>User</label>
                        <input type="text" name="db_user" required dir="ltr">
                    </div>
                    <div>
                        <label>Password</label>
                        <input type="password" name="db_pass" dir="ltr">
                    </div>
                </div>
                <label class="check"><input type="checkbox" name="create_db" value="1" checked> ایجاد دیتابیس در صورت عدم وجود</label>
            </div>

            <div class="section">
                <h2>سایت</h2>
                <label>نام سایت</label>
                <input type="text" name="app_name" value="موبارو" required>
                <label>آدرس دامنه</label>
                <input type="text" name="app_url" value="https://<?= htmlspecialchars($_SERVER['HTTP_HOST'] ?? 'mobaro.ir') ?>" required dir="ltr" placeholder="https://mobaro.ir">
            </div>

            <div class="section">
                <h2>حساب مدیر</h2>
                <label>شماره موبایل</label>
                <input type="text" name="phone" placeholder="۰۹۱۲۳۴۵۶۷۸۹" required dir="ltr">
                <div class="row">
                    <div>
                        <label>رمز عبور</label>
                        <input type="password" name="password" required dir="ltr" placeholder="حداقل ۶ کاراکتر">
                    </div>
                    <div>
                        <label>تکرار رمز</label>
                        <input type="password" name="password2" required dir="ltr">
                    </div>
                </div>
            </div>

            <label class="check"><input type="checkbox" name="with_seed" value="1" checked> وارد کردن داده‌های نمونه (دمو)</label>

            <button type="submit">نصب</button>
        </form>

    <?php else: ?>

        <div class="success">
            <strong>نصب با موفقیت انجام شد!</strong>
            فایل <code>.env</code> ساخته شد و دیتابیس آماده است.
            <?php if (isset($messages) && is_array($messages)): ?>
                <div class="log"><?= implode('<br>', array_map('htmlspecialchars', $messages)) ?></div>
            <?php endif; ?>
            <a href="/admin/login" style="color:#e11d48;font-weight:700;">ورود به پنل مدیریت</a>
        </div>
        <div class="warn">
            برای امنیت، فایل‌های <strong>install.php</strong> و <strong>install.lock</strong> را همین حالا از هاست حذف کنید.
        </div>

    <?php endif; ?>
</div>
</body>
</html>
