ALTER TABLE products
  ADD COLUMN IF NOT EXISTS old_price BIGINT AFTER price,
  ADD COLUMN IF NOT EXISTS brand VARCHAR(255) AFTER category,
  ADD COLUMN IF NOT EXISTS is_new TINYINT(1) DEFAULT 0 AFTER stock,
  ADD COLUMN IF NOT EXISTS is_sale TINYINT(1) DEFAULT 0 AFTER is_new;

CREATE TABLE IF NOT EXISTS reviews (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  user_name VARCHAR(255) NOT NULL,
  rating DECIMAL(2,1) NOT NULL DEFAULT 5.0,
  text TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);
